export enum userActionTypes {
	LOGIN = '@@AUTH/LOGIN',
	LOGOUT = '@@AUTH/LOGOUT',
	REQUEST_USER_SAGA = '@@USER/REQUEST_USER_SAGA',
	SET_USER_PALETTE = '@@USER/SET_USER_PALETTE',
	SET_USER_AGREEMENT = '@@USER/SET_USER_AGREEMENT',
	SET_USER_PRICE_AGR = '@@USER/SET_USER_PRICE_AGR',
}
