export enum authorizationActionTypes {
	AUTHENTICATE_WITH_LOGIN_AND_PASSWORD_SAGA = '@@AUTHORIZATION/AUTHENTICATE_WITH_LOGIN_AND_PASSWORD_SAGA',
	SEND_SMS_CODE_SAGA = '@@AUTHORIZATION/SEND_SMS_CODE_SAGA',
	// GET_ACCESS_TOKEN_SAGA = '@@AUTHORIZATION/GET_ACCESS_TOKEN_SAGA',
	GET_LOCAL_REFRESH_TOKEN_SAGA = '@@AUTHORIZATION/GET_LOCAL_REFRESH_TOKEN',
	SET_TOKENS = '@@AUTHORIZATION/SET_TOKENS',
	SET_REFRESH_TOKEN = '@@AUTHORIZATION/SET_REFRESH_TOKEN',
	TOGGLE_ISPENNDING = '@@AUTHORIZATION/TOGGLE_ISPENNDING',
	SET_AUTHORIZATION_STEP = '@@AUTHORIZATION/SET_AUTHORIZATION_STEP',
	SET_ACCESS_TOKEN = '@@AUTHORIZATION/SET_ACCESS_TOKEN',
}
